---
title: "Trabajo M1 Y M2"
author: 
  - 
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
    theme: journal
---

```{r setup, message = FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE,include = TRUE, message = FALSE)
```

**Carga de librerías a usar**   
```{r, include = TRUE}
pacman::p_load(tidyverse, ggplot2, forcats, ggtext, readxl, naniar, sf, plotly, gganimate, gifski, polArViz, geoAr)
options(scipen = 999)
```

**Carga de bases de datos a usar**
 
```{r echo=TRUE, eval=TRUE}
base_dptos_total <- read_excel("data/Salario-promedio-por-departamento.xlsx")
mapa_dptos <- read_sf ("data/departamentos_arg.geojson")
w_mean_dpto_priv_clae2 <- read.csv("data/w_mean_depto_total_clae2.csv")
diccionario <- read.csv("data/diccionario_clae2.csv")
provincias <- "data/provincia.json"
```

 Tarea 1: Los departamentos con mayores salarios, expresados en un mapa coroplético
 
```{r echo=TRUE, eval=TRUE}
caba <- st_read(provincias) %>% 
  filter(fna == "Ciudad Autónoma de Buenos Aires") %>% 
  select(geometry) %>% 
  mutate(provincia = "CABA")

caba <- st_transform(caba, 3857)

caba <- caba %>% 
  mutate(link = NA,
         codpcia = "02", #Le asigno un valor para futuros procesamientos
         departamen = NA,
         mujeres = NA,
         varones = NA,
         personas = NA,
         hogares = NA, 
         viv_part_h = NA,
         viv_part = NA, 
         codigo_departamento_indec = "2000") #Le asigno un valor para futuros procesamientos

mapa_dptos <- read_sf ("data/departamentos_arg.geojson")
st_crs(mapa_dptos)
mapa_dptos_mercator <- st_transform(mapa_dptos, 3857)

mapa_dptos_mercator <- mapa_dptos_mercator %>% 
  filter(provincia != "Ciudad Autónoma de Buenos Aires")

mapa_con_caba <- rbind(mapa_dptos_mercator, caba)

mapa_con_caba <- mapa_con_caba %>% 
  rename(codprov_censo = codpcia)

rm(caba, mapa_dptos, mapa_dptos_mercator)

#ggplot (mapa_con_caba)+
 # geom_sf ()

####Segunda etapa:
mapa_dptos_mercator <- mapa_con_caba %>%
  mutate(codigo_departamento_indec = as.numeric(codigo_departamento_indec))

#Achicamos la base para tener menos columnas, decidimos trabajar sólo con los datos de marzo 2023
base_dptos_3_23<- base_dptos_total %>%
  select(codigo_departamento_indec, m202303, provincia, departamento)

#Unificamos ambos archivos.
base_unificada <- mapa_dptos_mercator %>%
  left_join(base_dptos_3_23, by = "codigo_departamento_indec")

base_unificada <- base_unificada %>%
  mutate(cuartil4 = case_when(is.na(m202303) ~ "Sin datos",
                              m202303 >= quantile(m202303, probs = 0.75, na.rm = TRUE) ~ "Si",
                              TRUE ~ "No")) %>%
  select(m202303, cuartil4, codprov_censo)

mapa <- ggplot(base_unificada)+
  geom_sf(aes(fill= cuartil4))+
  scale_fill_viridis_d()+
  labs (title = "Departamentos del país con salarios promedios más elevados** (cuarto cuartil)",
        subtitle = "Argentina, marzo 2023.",
        fill= "Departamentos del cuarto cuartil de salarios",
        caption= "Elaboración propia en base a datos del Ministerio de desarrollo productivo")+
  theme_void()

polArViz::inset_caba(mapa)

```

**Los 5 sectores de actividad con salarios más bajos, expresados en un gráfico de
barras.**


```{r echo=TRUE, eval=TRUE}

grafico_T2 <- left_join(x = w_mean_dpto_priv_clae2, y = diccionario)%>%
  mutate(anio = year(fecha), mes = month(fecha))%>%
  filter(anio == 2023 & mes == 4 & w_mean >= 0)%>%
  group_by(letra_desc) %>%
  summarise(ingr_oc_princ_media = mean(x = w_mean))%>%
  mutate(ranking = row_number(ingr_oc_princ_media))%>%
  filter(ranking <= 5)%>%
  ggplot(aes(x = ingr_oc_princ_media, y = fct_reorder(letra_desc, ingr_oc_princ_media), fill = letra_desc))+
  geom_col()+
  theme_minimal()+
  scale_fill_viridis_d()+
  guides(fill= "none") +
  labs(title = "5 sectores de actividad con salarios más bajos",
       subtitle = "(Argentina, abril 2023)",
       x = "Ingreso medio",
       y = NULL,
       caption = "Fuente: Ministerio de Desarrollo Productivo")+
  theme(plot.title = element_markdown(face = 'bold'),
  axis.title.x = element_markdown())

grafico_T2

```

```{r echo=TRUE, eval=TRUE}
color_sectores <- c("A" = "darkorange", "B" = "red", "C" = "blue",
                       "D" = "yellow")

data_g_T3 <- left_join(x = w_mean_dpto_priv_clae2, y = diccionario) %>%
  filter(letra == "A" |letra == "B" |letra =="C" |letra =="D")%>%
  mutate(anio = year(fecha), mes = month(fecha))%>%
  filter(mes == 12)%>%
  group_by(letra, anio) %>%
  summarize(media_w_mean = mean(w_mean), .groups = "drop")%>%
  arrange(anio, desc(media_w_mean))%>%
  group_by(anio)%>%
  mutate(ranking = row_number())%>%
  filter(ranking <= 5)

g_T3 <- ggplot(data_g_T3) +
  geom_col(aes(x = media_w_mean, y = factor(ranking), fill = letra)) +
  geom_text(aes(x = media_w_mean, y = factor(ranking), label = letra)) +
  scale_fill_manual(values = color_sectores) +
  theme_minimal() +
  transition_time(anio) +
  labs(title = "Diciembre: {as.integer(frame_time)}", y = NULL, x = "Salario promedio")


g_T3 
```

